name: .NET Tests

on:
  push:
    branches: [ "main", "dev"]
    paths:
      - "src/**"
      - ".github/workflows/tests.yml"
  pull_request:
    branches: [ "main", "dev"]
    paths:
      - "src/**"
      - ".github/workflows/tests.yml"

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        config: [Debug, Release]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build projects
        run: dotnet build --no-restore -c ${{ matrix.config }}
      - name: Run tests
        run: dotnet test --no-build -v normal -c ${{ matrix.config }}
      