name: .NET Tests for Tiempito

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev"]

jobs:

  linux-tests:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore --ucr
    - name: Build
      run: dotnet build --no-restore -c Release-Linux
    - name: Test
      run: dotnet test --no-build -v normal -c Release-Linux

  win-tests:
    timeout-minutes: 15
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore --ucr
    - name: Build
      run: dotnet build --no-restore -c Release-Windows
    - name: Test
      run: dotnet test --no-build -v normal -c Release-Windows
      
    
      
